services:
  - type: web
    name: dreemz-analytics-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    plan: free
    healthCheckPath: /api/status
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.18"